/**
 * Pack and Game Mode Configuration Registry
 * Enterprise Mafia / Social Deduction Platform - Phase 1 Foundation
 */

import { GameMode, PackMetadata } from '../types/packs';

export const PACKS_CONFIG: Readonly<Record<GameMode, PackMetadata>> = {
  // === STANDARD PACKS ===
  BLITZ: {
    id: 'BLITZ',
    name: 'Blitz (5-7 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '1 Qatil (Mafiya), 1 Şərif (Müstəntiq), 1 Həkim, 1 Lusiferin Kölgəsi (Dəli), 1 Gözbağlayıcı, 2 Məsum Vətəndaş',
    minPlayers: 5,
    maxPlayers: 7,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 60,
      dayVotingSeconds: 30,
      nightBufferSeconds: 25,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  STANDARD: {
    id: 'STANDARD',
    name: 'Standart (8-11 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '2 Gizli Qatil (Mafiya), 1 Şərif (Müstəntiq), 1 Həkim, 1 Lusiferin Kölgəsi (Dəli), 1 Gözbağlayıcı, 1 Pataloqanatom, 4 Qonaq (Vətəndaş)',
    minPlayers: 8,
    maxPlayers: 11,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 75,
      nightBufferSeconds: 30,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  EXTENDED: {
    id: 'EXTENDED',
    name: 'Genişləndirilmiş (12-15 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '3 İcraçı Qatil (Mafiya), 1 Prokuror, 1 Vəkil, 1 Şantajçı, 1 Pataloqanatom, 1 Həkim, 7 Vətəndaş',
    minPlayers: 12,
    maxPlayers: 15,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 120,
      dayVotingSeconds: 45,
      nightBufferSeconds: 30,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  GRAND: {
    id: 'GRAND',
    name: 'Böyük (16-20 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '4 Mafiya, 1 Zaman Səyyahı, 1 Gözbağlayıcı, 1 İllüziyaçı, 1 Şərif, 1 Həkim, 11 Vətəndaş',
    minPlayers: 16,
    maxPlayers: 20,
    minTier: 'TIER_2',
    hostWaiverAllowed: true,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 150,
      dayVotingSeconds: 60,
      nightBufferSeconds: 75,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: true,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  EPIC: {
    id: 'EPIC',
    name: 'Epik (21-24 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '5 Mafiya, 2 Şərif, 2 Həkim, 1 İnkvizitor, 1 Pataloqanatom, 1 Kuklaçı, 12 Vətəndaş',
    minPlayers: 21,
    maxPlayers: 24,
    minTier: 'TIER_2',
    hostWaiverAllowed: true,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayRegionalCaucusSeconds: 180,
      dayCentralAssemblySeconds: 150,
      dayVotingSeconds: 60,
      nightBufferSeconds: 45,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: true,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  MASSIVE: {
    id: 'MASSIVE',
    name: 'Kütləvi (25-30 Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '6 Mafiya, 2 Şərif, 2 Həkim, 2 Müstəqil Qatil, 1 Fədai, 1 Casus, 16 Vətəndaş',
    minPlayers: 25,
    maxPlayers: 30,
    minTier: 'TIER_3',
    hostWaiverAllowed: true,
    platformAdminRequired: false,
    requiresExamProof: true,
    defaultTimings: {
      dayRegionalCaucusSeconds: 240,
      dayCentralAssemblySeconds: 150,
      dayVotingSeconds: 150,
      nightBufferSeconds: 45,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_3',
      hostWaiverAllowed: true,
      platformAdminRequired: false,
      requiresExamProof: true,
    },
  },

  LIMITLESS: {
    id: 'LIMITLESS',
    name: 'Sərhədsiz (30+ Oyunçu)',
    tagline: '',
    description: '',
    roleBreakdown: '8 Mafiya (Xaç Atası, Don, Şantajçı, Kuklaçı), 3 Şərif, 3 Həkim, 2 Pataloqanatom, 23 Vətəndaş',
    minPlayers: 30,
    maxPlayers: 39,
    minTier: 'TIER_3',
    hostWaiverAllowed: true,
    platformAdminRequired: false,
    requiresExamProof: true,
    defaultTimings: {
      dayRegionalCaucusSeconds: 300,
      dayCentralAssemblySeconds: 180,
      dayVotingSeconds: 180,
      nightBufferSeconds: 120,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_3',
      hostWaiverAllowed: true,
      platformAdminRequired: false,
      requiresExamProof: true,
    },
  },

  CUSTOM_LOBBY: {
    id: 'CUSTOM_LOBBY',
    name: 'Xüsusi Otaq',
    tagline: '',
    description: '',
    roleBreakdown: 'Sərbəst Seçim (Bütün Rollar və Xüsusi Qabiliyyətlər Əlçatandır)',
    minPlayers: 5,
    maxPlayers: 50,
    minTier: 'TIER_1',
    hostWaiverAllowed: true,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 120,
      dayVotingSeconds: 45,
      nightBufferSeconds: 30,
    },
    isMinigame: false,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: true,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  // === MINIGAMES ===
  CATENACCIO: {
    id: 'CATENACCIO',
    name: 'Catenaccio',
    tagline: '',
    description: '',
    roleBreakdown: '1 Tək Snayper, 4 Zirehli Müdafiəçi, 1 Həkim, 6 Vətəndaş',
    minPlayers: 10,
    maxPlayers: 12,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  STANFORD_PRISON: {
    id: 'STANFORD_PRISON',
    name: 'Stanford Prison',
    tagline: '',
    description: '',
    roleBreakdown: '1 Baş Nəzarətçi, 3 Nəzarətçi, 1 Qatil Məhbus, 1 Həkim, 10 Məhbus',
    minPlayers: 12,
    maxPlayers: 16,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 270,
      dayVotingSeconds: 75,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  OPERATION_VALKYRIE: {
    id: 'OPERATION_VALKYRIE',
    name: 'Operation Valkyrie',
    tagline: '',
    description: '',
    roleBreakdown: '1 Diktator, 3 Qəsdçi, 2 Mühafizəçi, 1 Həkim, 7 Vətəndaş',
    minPlayers: 10,
    maxPlayers: 14,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 25,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  THE_DAY_THE_EARTH_STOOD_STILL: {
    id: 'THE_DAY_THE_EARTH_STOOD_STILL',
    name: 'The Day the Earth Stood Still',
    tagline: '',
    description: '',
    roleBreakdown: '1 Klaatu (Dünyanı Donduran), 1 Qort İdarəçisi, 2 Yadplanetli, 1 Həkim, 11 Vətəndaş',
    minPlayers: 12,
    maxPlayers: 16,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 120,
      dayVotingSeconds: 75,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  DANTES_INFERNO: {
    id: 'DANTES_INFERNO',
    name: "Dante's Inferno",
    tagline: '',
    description: '',
    roleBreakdown: '3 Malebranche İblisi, 1 Vergili (Şərif), 1 Mərhəmət Mələyi, 1 Lusiferin Kölgəsi (Dəli), 7 Günahkar Ruh',
    minPlayers: 11,
    maxPlayers: 13,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  CHERNOBYL_EXCLUSION_ZONE: {
    id: 'CHERNOBYL_EXCLUSION_ZONE',
    name: 'Çernobıl: Təcrid Zonası',
    tagline: '',
    description: '',
    roleBreakdown: '1 Dozimetrist (Şərif), 2 Çernobıl Likvidatoru (Həkim), 3 Radiasiyalı Mutant (Mafiya), 1 Bioloji Tədqiqatçı, 5 Sağ Qalan Vətəndaş',
    minPlayers: 10,
    maxPlayers: 14,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  CYBERPUNK_NEO_BAKU: {
    id: 'CYBERPUNK_NEO_BAKU',
    name: 'Cyberpunk 2077: Neo-Bakı',
    tagline: '',
    description: '',
    roleBreakdown: '1 Korporativ Kəşfiyyatçı (Şərif), 2 Netrunner Hakker (İllüziyaçı), 3 Qara Şəbəkə Qatili (Mafiya), 1 Neyro-Cərrah (Həkim), 7 Xaker Vətəndaş',
    minPlayers: 12,
    maxPlayers: 16,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 270,
      dayVotingSeconds: 75,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  BERMUDA_TRIANGLE: {
    id: 'BERMUDA_TRIANGLE',
    name: 'Bermud Üçbucağı: Ruhlar Donanması',
    tagline: '',
    description: '',
    roleBreakdown: '1 Şturman Naviqator (Şərif), 1 Gəmi Həkimi, 3 Ruh Qulduru (Mafiya), 1 Dəniz Əfsanəsi Qoruyucusu, 6 İtmiş Dənizçi',
    minPlayers: 10,
    maxPlayers: 14,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  MIDNIGHT_SEANCE: {
    id: 'MIDNIGHT_SEANCE',
    name: 'Gecəyarısı Seansı: Qanlı Meri',
    tagline: '',
    description: '',
    roleBreakdown: '1 Ruhçağıran Medium (Şərif), 1 Ekzorsist Ruhani (Həkim), 3 Qara Ayin Kölgəsi (Mafiya), 1 Poltergeyst (Dəli), 7 Seans İştirakçısı',
    minPlayers: 11,
    maxPlayers: 15,
    minTier: 'TIER_2',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 90,
      dayVotingSeconds: 30,
      nightBufferSeconds: 30,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_2',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  SHERLOCK_BAKER_STREET: {
    id: 'SHERLOCK_BAKER_STREET',
    name: 'Baker Street: Holms vs Moriarti',
    tagline: '',
    description: '',
    roleBreakdown: '1 Şerlok Holms (Baş Müstəntiq), 1 Dr. Con Vatson (Həkim), 2 Moriarti Şəbəkəsi (Mafiya), 1 İren Adler (Müstəqil Casus), 5 London Sakini',
    minPlayers: 8,
    maxPlayers: 12,
    minTier: 'TIER_1',
    hostWaiverAllowed: false,
    platformAdminRequired: false,
    requiresExamProof: false,
    defaultTimings: {
      dayCentralAssemblySeconds: 210,
      dayVotingSeconds: 30,
      nightBufferSeconds: 25,
    },
    isMinigame: true,
    isAllIn: false,
    accessRule: {
      minTier: 'TIER_1',
      hostWaiverAllowed: false,
      platformAdminRequired: false,
      requiresExamProof: false,
    },
  },

  // === ALL-IN GRAND MODE ===
  ALL_IN: {
    id: 'ALL_IN',
    name: 'All-In',
    tagline: '',
    description: '',
    roleBreakdown: '10 Mafiya, 16 İctimai Vəzifəli Şəxs, 12 Gizli İstedadlı, 12 Vətəndaş',
    minPlayers: 40,
    maxPlayers: 50,
    minTier: 'TIER_3',
    hostWaiverAllowed: false,
    platformAdminRequired: true,
    requiresExamProof: true,
    defaultTimings: {
      dayRegionalCaucusSeconds: 360,
      dayCentralAssemblySeconds: 180,
      dayVotingSeconds: 180,
      nightBufferSeconds: 120,
    },
    isMinigame: false,
    isAllIn: true,
    accessRule: {
      minTier: 'TIER_3',
      hostWaiverAllowed: false,
      platformAdminRequired: true,
      requiresExamProof: true,
    },
  },
};

export function getPackMetadata(mode: GameMode): PackMetadata {
  return PACKS_CONFIG[mode];
}
